CREATE TABLE IF NOT EXISTS Product(
       Id INT GENERATED BY DEFAULT AS IDENTITY ,
       ProductCode VARCHAR(10) NOT NULL,
       ProductName  VARCHAR(50) NOT NULL,
       Category CHAR(5) NOT NULL,
       CONSTRAINT CropProduct_PK  PRIMARY KEY(Id)
);


CREATE TABLE IF NOT EXISTS Market(
       Id INT GENERATED BY DEFAULT AS IDENTITY ,
       MarketCode varchar(10) NOT NUll,
       MarketName varchar(50) NOT NULL,
       Category CHAR(5) NOT NULL,
       CONSTRAINT CropMarket_PK PRIMARY KEY(Id)
);



CREATE TABLE IF NOT EXISTS Traded(
       Id INT GENERATED BY DEFAULT AS IDENTITY ,
       TradedDate DATE NOT NULL ,
       ProductId int NOT NULL,
       MarketId int NOT NULL,
       Category CHAR(5) NOT NULL,
       AvgPrice NUMERIC NOT NULL,
       TransQuantity NUMERIC NOT NULL,
       CONSTRAINT Traded_pk PRIMARY KEY(Id),
       CONSTRAINT Market_FK FOREIGN KEY(MarketId) REFERENCES Market(Id),
       CONSTRAINT Product_FK FOREIGN KEY(ProductId) REFERENCES Product(Id)

);
